name: Create Release ZIP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete old tag
        run: |
          git push --delete origin latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Archive
        run: |
          rm -rf MethodDungeonTools
          mkdir -p MethodDungeonTools
          rsync -av . MethodDungeonTools --exclude .git --exclude .github --exclude MethodDungeonTools --exclude MDT.zip
          zip -r MDT.zip MethodDungeonTools

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          files: MDT.zip
          tag_name: latest
          name: "Latest Version"
          body: |
            ${{ github.event.head_commit.message }}

            _Обновлено автоматически: ${{ github.event.head_commit.timestamp }}_
          prerelease: false
          make_latest: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
